// ============================================================
//  DATOS DEL TORNEO
//  Editá este archivo para cambiar partidos, sedes y precios.
// ============================================================

// Categorías de tribuna (precio en USD por entrada)
const CATEGORIAS = [
  { id: "cat1", nombre: "Categoría 1", detalle: "Lateral premium · platea baja", precio: 450 },
  { id: "cat2", nombre: "Categoría 2", detalle: "Tribuna media · vista central", precio: 280 },
  { id: "cat3", nombre: "Categoría 3", detalle: "Cabecera · detrás del arco", precio: 180 },
  { id: "cat4", nombre: "Categoría 4", detalle: "General · acceso al estadio", precio: 95 },
];

// Lista de partidos
const PARTIDOS = [
  {
    id: "m_a01",
    equipo1: "México",
    equipo2: "Sudáfrica",
    flag1: "https://flagcdn.com/mx.svg",
    flag2: "https://flagcdn.com/za.svg",
    estadio: "Estadio Ciudad de México (Ciudad de México)",
    fecha: "2026-06-11T00:00:00.000Z",
    grupo: "A",
    precio: "180",
    resultado: "2-0",
    goles1: 2,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_a02",
    equipo1: "República de Corea",
    equipo2: "Chequia",
    flag1: "https://flagcdn.com/kr.svg",
    flag2: "https://flagcdn.com/cz.svg",
    estadio: "Estadio Guadalajara (Guadalajara)",
    fecha: "2026-06-11T00:00:00.000Z",
    grupo: "A",
    precio: "180",
    resultado: "2-1",
    goles1: 2,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_a03",
    equipo1: "Chequia",
    equipo2: "Sudáfrica",
    flag1: "https://flagcdn.com/cz.svg",
    flag2: "https://flagcdn.com/za.svg",
    estadio: "Estadio Atlanta (Atlanta)",
    fecha: "2026-06-13T00:00:00.000Z",
    grupo: "A",
    precio: "180",
    resultado: "1-1",
    goles1: 1,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_a04",
    equipo1: "México",
    equipo2: "República de Corea",
    flag1: "https://flagcdn.com/mx.svg",
    flag2: "https://flagcdn.com/kr.svg",
    estadio: "Estadio Guadalajara (Guadalajara)",
    fecha: "2026-06-13T00:00:00.000Z",
    grupo: "A",
    precio: "180",
    resultado: "1-0",
    goles1: 1,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_a05",
    equipo1: "Chequia",
    equipo2: "México",
    flag1: "https://flagcdn.com/cz.svg",
    flag2: "https://flagcdn.com/mx.svg",
    estadio: "Estadio Ciudad de México (Ciudad de México)",
    fecha: "2026-06-24T00:00:00.000Z",
    grupo: "A",
    precio: "180",
    resultado: "0-3",
    goles1: 0,
    goles2: 3,
    estado: "finalizado"
  },
  {
    id: "m_a06",
    equipo1: "Sudáfrica",
    equipo2: "República de Corea",
    flag1: "https://flagcdn.com/za.svg",
    flag2: "https://flagcdn.com/kr.svg",
    estadio: "Estadio Monterrey (Monterrey)",
    fecha: "2026-06-24T00:00:00.000Z",
    grupo: "A",
    precio: "180",
    resultado: "1-0",
    goles1: 1,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_b01",
    equipo1: "Canadá",
    equipo2: "Bosnia y Herzegovina",
    flag1: "https://flagcdn.com/ca.svg",
    flag2: "https://flagcdn.com/ba.svg",
    estadio: "Estadio de Toronto (Toronto)",
    fecha: "2026-06-12T00:00:00.000Z",
    grupo: "B",
    precio: "180",
    resultado: "1-1",
    goles1: 1,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_b02",
    equipo1: "Catar",
    equipo2: "Suiza",
    flag1: "https://flagcdn.com/qa.svg",
    flag2: "https://flagcdn.com/ch.svg",
    estadio: "Estadio de la Bahía de San Francisco (Área de la Bahía de San Francisco)",
    fecha: "2026-06-13T00:00:00.000Z",
    grupo: "B",
    precio: "180",
    resultado: "1-1",
    goles1: 1,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_b03",
    equipo1: "Suiza",
    equipo2: "Bosnia y Herzegovina",
    flag1: "https://flagcdn.com/ch.svg",
    flag2: "https://flagcdn.com/ba.svg",
    estadio: "SoFi Stadium (Inglewood)",
    fecha: "2026-06-18T00:00:00.000Z",
    grupo: "B",
    precio: "180",
    resultado: "4-1",
    goles1: 4,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_b04",
    equipo1: "Canadá",
    equipo2: "Catar",
    flag1: "https://flagcdn.com/ca.svg",
    flag2: "https://flagcdn.com/qa.svg",
    estadio: "Estadio BC Place Vancouver (Vancouver)",
    fecha: "2026-06-18T00:00:00.000Z",
    grupo: "B",
    precio: "180",
    resultado: "6-0",
    goles1: 6,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_b05",
    equipo1: "Bosnia y Herzegovina",
    equipo2: "Catar",
    flag1: "https://flagcdn.com/ba.svg",
    flag2: "https://flagcdn.com/qa.svg",
    estadio: "Lumen Field (Seattle)",
    fecha: "2026-06-24T00:00:00.000Z",
    grupo: "B",
    precio: "180",
    resultado: "3-1",
    goles1: 3,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_b06",
    equipo1: "Suiza",
    equipo2: "Canadá",
    flag1: "https://flagcdn.com/ch.svg",
    flag2: "https://flagcdn.com/ca.svg",
    estadio: "Estadio BC Place Vancouver (Vancouver)",
    fecha: "2026-06-24T00:00:00.000Z",
    grupo: "B",
    precio: "180",
    resultado: "2-1",
    goles1: 2,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_c01",
    equipo1: "Brasil",
    equipo2: "Marruecos",
    flag1: "https://flagcdn.com/br.svg",
    flag2: "https://flagcdn.com/ma.svg",
    estadio: "Estadio Nueva York/Nueva Jersey (Nueva Jersey)",
    fecha: "2026-06-13T00:00:00.000Z",
    grupo: "C",
    precio: "180",
    resultado: "1-1",
    goles1: 1,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_c02",
    equipo1: "Haití",
    equipo2: "Escocia",
    flag1: "https://flagcdn.com/ht.svg",
    flag2: "https://flagcdn.com/gb-sct.svg",
    estadio: "Estadio Boston (Boston)",
    fecha: "2026-06-13T00:00:00.000Z",
    grupo: "C",
    precio: "180",
    resultado: "0-1",
    goles1: 0,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_c03",
    equipo1: "Escocia",
    equipo2: "Marruecos",
    flag1: "https://flagcdn.com/gb-sct.svg",
    flag2: "https://flagcdn.com/ma.svg",
    estadio: "Estadio Boston (Boston)",
    fecha: "2026-06-19T00:00:00.000Z",
    grupo: "C",
    precio: "180",
    resultado: "0-1",
    goles1: 0,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_c04",
    equipo1: "Brasil",
    equipo2: "Haití",
    flag1: "https://flagcdn.com/br.svg",
    flag2: "https://flagcdn.com/ht.svg",
    estadio: "Estadio Filadelfia (Filadelfia)",
    fecha: "2026-06-19T00:00:00.000Z",
    grupo: "C",
    precio: "180",
    resultado: "3-0",
    goles1: 3,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_c05",
    equipo1: "Marruecos",
    equipo2: "Haití",
    flag1: "https://flagcdn.com/ma.svg",
    flag2: "https://flagcdn.com/ht.svg",
    estadio: "Estadio Atlanta (Atlanta)",
    fecha: "2026-06-24T00:00:00.000Z",
    grupo: "C",
    precio: "180",
    resultado: "4-2",
    goles1: 4,
    goles2: 2,
    estado: "finalizado"
  },
  {
    id: "m_c06",
    equipo1: "Escocia",
    equipo2: "Brasil",
    flag1: "https://flagcdn.com/gb-sct.svg",
    flag2: "https://flagcdn.com/br.svg",
    estadio: "Estadio Miami (Miami)",
    fecha: "2026-06-24T00:00:00.000Z",
    grupo: "C",
    precio: "180",
    resultado: "0-3",
    goles1: 0,
    goles2: 3,
    estado: "finalizado"
  },
  {
    id: "m_d01",
    equipo1: "EE. UU.",
    equipo2: "Paraguay",
    flag1: "https://flagcdn.com/us.svg",
    flag2: "https://flagcdn.com/py.svg",
    estadio: "Estadio Los Angeles (Los Ángeles)",
    fecha: "2026-06-12T00:00:00.000Z",
    grupo: "D",
    precio: "180",
    resultado: "4-1",
    goles1: 4,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_d02",
    equipo1: "Australia",
    equipo2: "Turquía",
    flag1: "https://flagcdn.com/au.svg",
    flag2: "https://flagcdn.com/tr.svg",
    estadio: "Estadio BC Place Vancouver (Vancouver)",
    fecha: "2026-06-14T00:00:00.000Z",
    grupo: "D",
    precio: "180",
    resultado: "2-0",
    goles1: 2,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_d03",
    equipo1: "EE. UU.",
    equipo2: "Australia",
    flag1: "https://flagcdn.com/us.svg",
    flag2: "https://flagcdn.com/au.svg",
    estadio: "Estadio de Seattle (Seattle)",
    fecha: "2026-06-19T00:00:00.000Z",
    grupo: "D",
    precio: "180",
    resultado: "2-0",
    goles1: 2,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_d04",
    equipo1: "Turquía",
    equipo2: "Paraguay",
    flag1: "https://flagcdn.com/tr.svg",
    flag2: "https://flagcdn.com/py.svg",
    estadio: "Estadio de la Bahía de San Francisco (Área de la Bahía de San Francisco)",
    fecha: "2026-06-20T00:00:00.000Z",
    grupo: "D",
    precio: "180",
    resultado: "0-1",
    goles1: 0,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_d05",
    equipo1: "Turquía",
    equipo2: "EE. UU.",
    flag1: "https://flagcdn.com/tr.svg",
    flag2: "https://flagcdn.com/us.svg",
    estadio: "Estadio Los Angeles (Los Ángeles)",
    fecha: "2026-06-25T00:00:00.000Z",
    grupo: "D",
    precio: "180",
    resultado: "3-2",
    goles1: 3,
    goles2: 2,
    estado: "finalizado"
  },
  {
    id: "m_d06",
    equipo1: "Paraguay",
    equipo2: "Australia",
    flag1: "https://flagcdn.com/py.svg",
    flag2: "https://flagcdn.com/au.svg",
    estadio: "Estadio de la Bahía de San Francisco (Área de la Bahía de San Francisco)",
    fecha: "2026-06-25T00:00:00.000Z",
    grupo: "D",
    precio: "180",
    resultado: "0-0",
    goles1: 0,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_e01",
    equipo1: "Alemania",
    equipo2: "Curazao",
    flag1: "https://flagcdn.com/de.svg",
    flag2: "https://flagcdn.com/cw.svg",
    estadio: "Estadio Houston (Houston)",
    fecha: "2026-06-14T00:00:00.000Z",
    grupo: "E",
    precio: "180",
    resultado: "7-1",
    goles1: 7,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_e02",
    equipo1: "Costa de Marfil",
    equipo2: "Ecuador",
    flag1: "https://flagcdn.com/ci.svg",
    flag2: "https://flagcdn.com/ec.svg",
    estadio: "Estadio Filadelfia (Filadelfia)",
    fecha: "2026-06-14T00:00:00.000Z",
    grupo: "E",
    precio: "180",
    resultado: "1-0",
    goles1: 1,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_e03",
    equipo1: "Alemania",
    equipo2: "Costa de Marfil",
    flag1: "https://flagcdn.com/de.svg",
    flag2: "https://flagcdn.com/ci.svg",
    estadio: "Estadio de Toronto (Toronto)",
    fecha: "2026-06-20T00:00:00.000Z",
    grupo: "E",
    precio: "180",
    resultado: "2-1",
    goles1: 2,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_e04",
    equipo1: "Ecuador",
    equipo2: "Curazao",
    flag1: "https://flagcdn.com/ec.svg",
    flag2: "https://flagcdn.com/cw.svg",
    estadio: "Estadio Kansas City (Kansas City)",
    fecha: "2026-06-20T00:00:00.000Z",
    grupo: "E",
    precio: "180",
    resultado: "0-0",
    goles1: 0,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_e05",
    equipo1: "Curazao",
    equipo2: "Costa de Marfil",
    flag1: "https://flagcdn.com/cw.svg",
    flag2: "https://flagcdn.com/ci.svg",
    estadio: "Estadio Filadelfia (Filadelfia)",
    fecha: "2026-06-25T00:00:00.000Z",
    grupo: "E",
    precio: "180",
    resultado: "0-2",
    goles1: 0,
    goles2: 2,
    estado: "finalizado"
  },
  {
    id: "m_e06",
    equipo1: "Ecuador",
    equipo2: "Alemania",
    flag1: "https://flagcdn.com/ec.svg",
    flag2: "https://flagcdn.com/de.svg",
    estadio: "Estadio Nueva York/Nueva Jersey (Nueva Jersey)",
    fecha: "2026-06-25T00:00:00.000Z",
    grupo: "E",
    precio: "180",
    resultado: "2-1",
    goles1: 2,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_f01",
    equipo1: "Países Bajos",
    equipo2: "Japón",
    flag1: "https://flagcdn.com/nl.svg",
    flag2: "https://flagcdn.com/jp.svg",
    estadio: "Estadio Dallas (Dallas)",
    fecha: "2026-06-14T00:00:00.000Z",
    grupo: "F",
    precio: "180",
    resultado: "2-2",
    goles1: 2,
    goles2: 2,
    estado: "finalizado"
  },
  {
    id: "m_f02",
    equipo1: "Suecia",
    equipo2: "Túnez",
    flag1: "https://flagcdn.com/se.svg",
    flag2: "https://flagcdn.com/tn.svg",
    estadio: "Estadio Monterrey (Monterrey)",
    fecha: "2026-06-14T00:00:00.000Z",
    grupo: "F",
    precio: "180",
    resultado: "5-1",
    goles1: 5,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_f03",
    equipo1: "Túnez",
    equipo2: "Japón",
    flag1: "https://flagcdn.com/tn.svg",
    flag2: "https://flagcdn.com/jp.svg",
    estadio: "Estadio Monterrey (Monterrey)",
    fecha: "2026-06-21T00:00:00.000Z",
    grupo: "F",
    precio: "180",
    resultado: "0-4",
    goles1: 0,
    goles2: 4,
    estado: "finalizado"
  },
  {
    id: "m_f04",
    equipo1: "Países Bajos",
    equipo2: "Suecia",
    flag1: "https://flagcdn.com/nl.svg",
    flag2: "https://flagcdn.com/se.svg",
    estadio: "Estadio Houston (Houston)",
    fecha: "2026-06-20T00:00:00.000Z",
    grupo: "F",
    precio: "180",
    resultado: "5-1",
    goles1: 5,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_f05",
    equipo1: "Japón",
    equipo2: "Suecia",
    flag1: "https://flagcdn.com/jp.svg",
    flag2: "https://flagcdn.com/se.svg",
    estadio: "Estadio Dallas (Dallas)",
    fecha: "2026-06-25T00:00:00.000Z",
    grupo: "F",
    precio: "180",
    resultado: "1-1",
    goles1: 1,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_f06",
    equipo1: "Túnez",
    equipo2: "Países Bajos",
    flag1: "https://flagcdn.com/tn.svg",
    flag2: "https://flagcdn.com/nl.svg",
    estadio: "Estadio Kansas City (Kansas City)",
    fecha: "2026-06-25T00:00:00.000Z",
    grupo: "F",
    precio: "180",
    resultado: "1-3",
    goles1: 1,
    goles2: 3,
    estado: "finalizado"
  },
  {
    id: "m_g01",
    equipo1: "Bélgica",
    equipo2: "Egipto",
    flag1: "https://flagcdn.com/be.svg",
    flag2: "https://flagcdn.com/eg.svg",
    estadio: "Estadio de Seattle (Seattle)",
    fecha: "2026-06-15T00:00:00.000Z",
    grupo: "G",
    precio: "180",
    resultado: "1-1",
    goles1: 1,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_g02",
    equipo1: "RI de Irán",
    equipo2: "Nueva Zelanda",
    flag1: "https://flagcdn.com/ir.svg",
    flag2: "https://flagcdn.com/nz.svg",
    estadio: "Estadio Los Angeles (Los Ángeles)",
    fecha: "2026-06-15T00:00:00.000Z",
    grupo: "G",
    precio: "180",
    resultado: "2-2",
    goles1: 2,
    goles2: 2,
    estado: "finalizado"
  },
  {
    id: "m_g03",
    equipo1: "Bélgica",
    equipo2: "RI de Irán",
    flag1: "https://flagcdn.com/be.svg",
    flag2: "https://flagcdn.com/ir.svg",
    estadio: "Estadio Los Angeles (Los Ángeles)",
    fecha: "2026-06-21T00:00:00.000Z",
    grupo: "G",
    precio: "180",
    resultado: "0-0",
    goles1: 0,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_g04",
    equipo1: "Nueva Zelanda",
    equipo2: "Egipto",
    flag1: "https://flagcdn.com/nz.svg",
    flag2: "https://flagcdn.com/eg.svg",
    estadio: "Estadio BC Place Vancouver (Vancouver)",
    fecha: "2026-06-21T00:00:00.000Z",
    grupo: "G",
    precio: "180",
    resultado: "1-3",
    goles1: 1,
    goles2: 3,
    estado: "finalizado"
  },
  {
    id: "m_g05",
    equipo1: "Egipto",
    equipo2: "RI de Irán",
    flag1: "https://flagcdn.com/eg.svg",
    flag2: "https://flagcdn.com/ir.svg",
    estadio: "Estadio de Seattle (Seattle)",
    fecha: "2026-06-27T00:00:00.000Z",
    grupo: "G",
    precio: "180",
    resultado: "1-1",
    goles1: 1,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_g06",
    equipo1: "Nueva Zelanda",
    equipo2: "Bélgica",
    flag1: "https://flagcdn.com/nz.svg",
    flag2: "https://flagcdn.com/be.svg",
    estadio: "Estadio BC Place Vancouver (Vancouver)",
    fecha: "2026-06-27T00:00:00.000Z",
    grupo: "G",
    precio: "180",
    resultado: "1-5",
    goles1: 1,
    goles2: 5,
    estado: "finalizado"
  },
  {
    id: "m_h01",
    equipo1: "España",
    equipo2: "Islas de Cabo Verde",
    flag1: "https://flagcdn.com/es.svg",
    flag2: "https://flagcdn.com/cv.svg",
    estadio: "Estadio Atlanta (Atlanta)",
    fecha: "2026-06-15T00:00:00.000Z",
    grupo: "H",
    precio: "180",
    resultado: "0-0",
    goles1: 0,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_h02",
    equipo1: "Arabia Saudí",
    equipo2: "Uruguay",
    flag1: "https://flagcdn.com/sa.svg",
    flag2: "https://flagcdn.com/uy.svg",
    estadio: "Estadio Miami (Miami)",
    fecha: "2026-06-15T00:00:00.000Z",
    grupo: "H",
    precio: "180",
    resultado: "1-1",
    goles1: 1,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_h03",
    equipo1: "España",
    equipo2: "Arabia Saudí",
    flag1: "https://flagcdn.com/es.svg",
    flag2: "https://flagcdn.com/sa.svg",
    estadio: "Estadio Atlanta (Atlanta)",
    fecha: "2026-06-21T00:00:00.000Z",
    grupo: "H",
    precio: "180",
    resultado: "4-0",
    goles1: 4,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_h04",
    equipo1: "Uruguay",
    equipo2: "Islas de Cabo Verde",
    flag1: "https://flagcdn.com/uy.svg",
    flag2: "https://flagcdn.com/cv.svg",
    estadio: "Estadio Miami (Miami)",
    fecha: "2026-06-21T00:00:00.000Z",
    grupo: "H",
    precio: "180",
    resultado: "2-2",
    goles1: 2,
    goles2: 2,
    estado: "finalizado"
  },
  {
    id: "m_h05",
    equipo1: "Islas de Cabo Verde",
    equipo2: "Arabia Saudí",
    flag1: "https://flagcdn.com/cv.svg",
    flag2: "https://flagcdn.com/sa.svg",
    estadio: "Estadio Houston (Houston)",
    fecha: "2026-06-26T00:00:00.000Z",
    grupo: "H",
    precio: "180",
    resultado: "0-0",
    goles1: 0,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_h06",
    equipo1: "Uruguay",
    equipo2: "España",
    flag1: "https://flagcdn.com/uy.svg",
    flag2: "https://flagcdn.com/es.svg",
    estadio: "Estadio Guadalajara (Guadalajara)",
    fecha: "2026-06-26T00:00:00.000Z",
    grupo: "H",
    precio: "180",
    resultado: "0-1",
    goles1: 0,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_i01",
    equipo1: "Francia",
    equipo2: "Senegal",
    flag1: "https://flagcdn.com/fr.svg",
    flag2: "https://flagcdn.com/sn.svg",
    estadio: "Estadio Nueva York/Nueva Jersey (Nueva Jersey)",
    fecha: "2026-06-16T00:00:00.000Z",
    grupo: "I",
    precio: "180",
    resultado: "3-1",
    goles1: 3,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_i02",
    equipo1: "Irak",
    equipo2: "Noruega",
    flag1: "https://flagcdn.com/iq.svg",
    flag2: "https://flagcdn.com/no.svg",
    estadio: "Estadio Boston (Boston)",
    fecha: "2026-06-16T00:00:00.000Z",
    grupo: "I",
    precio: "180",
    resultado: "1-4",
    goles1: 1,
    goles2: 4,
    estado: "finalizado"
  },
  {
    id: "m_i03",
    equipo1: "Francia",
    equipo2: "Irak",
    flag1: "https://flagcdn.com/fr.svg",
    flag2: "https://flagcdn.com/iq.svg",
    estadio: "Estadio Filadelfia (Filadelfia)",
    fecha: "2026-06-22T00:00:00.000Z",
    grupo: "I",
    precio: "180",
    resultado: "3-0",
    goles1: 3,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_i04",
    equipo1: "Noruega",
    equipo2: "Senegal",
    flag1: "https://flagcdn.com/no.svg",
    flag2: "https://flagcdn.com/sn.svg",
    estadio: "Estadio Nueva York/Nueva Jersey (Nueva Jersey)",
    fecha: "2026-06-22T00:00:00.000Z",
    grupo: "I",
    precio: "180",
    resultado: "3-2",
    goles1: 3,
    goles2: 2,
    estado: "finalizado"
  },
  {
    id: "m_i05",
    equipo1: "Noruega",
    equipo2: "Francia",
    flag1: "https://flagcdn.com/no.svg",
    flag2: "https://flagcdn.com/fr.svg",
    estadio: "Estadio Boston (Boston)",
    fecha: "2026-06-26T00:00:00.000Z",
    grupo: "I",
    precio: "180",
    resultado: "1-4",
    goles1: 1,
    goles2: 4,
    estado: "finalizado"
  },
  {
    id: "m_i06",
    equipo1: "Senegal",
    equipo2: "Irak",
    flag1: "https://flagcdn.com/sn.svg",
    flag2: "https://flagcdn.com/iq.svg",
    estadio: "Estadio de Toronto (Toronto)",
    fecha: "2026-06-26T00:00:00.000Z",
    grupo: "I",
    precio: "180",
    resultado: "5-0",
    goles1: 5,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_j01",
    equipo1: "Argentina",
    equipo2: "Argelia",
    flag1: "https://flagcdn.com/ar.svg",
    flag2: "https://flagcdn.com/dz.svg",
    estadio: "Estadio Kansas City (Kansas City)",
    fecha: "2026-06-16T00:00:00.000Z",
    grupo: "J",
    precio: "180",
    resultado: "3-0",
    goles1: 3,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_j02",
    equipo1: "Austria",
    equipo2: "Jordania",
    flag1: "https://flagcdn.com/at.svg",
    flag2: "https://flagcdn.com/jo.svg",
    estadio: "Estadio de la Bahía de San Francisco (Área de la Bahía de San Francisco)",
    fecha: "2026-06-17T00:00:00.000Z",
    grupo: "J",
    precio: "180",
    resultado: "3-1",
    goles1: 3,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_j03",
    equipo1: "Argentina",
    equipo2: "Austria",
    flag1: "https://flagcdn.com/ar.svg",
    flag2: "https://flagcdn.com/at.svg",
    estadio: "Estadio Dallas (Dallas)",
    fecha: "2026-06-22T00:00:00.000Z",
    grupo: "J",
    precio: "180",
    resultado: "2-0",
    goles1: 2,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_j04",
    equipo1: "Jordania",
    equipo2: "Argelia",
    flag1: "https://flagcdn.com/jo.svg",
    flag2: "https://flagcdn.com/dz.svg",
    estadio: "Estadio de la Bahía de San Francisco (Área de la Bahía de San Francisco)",
    fecha: "2026-06-23T00:00:00.000Z",
    grupo: "J",
    precio: "180",
    resultado: "1-2",
    goles1: 1,
    goles2: 2,
    estado: "finalizado"
  },
  {
    id: "m_j05",
    equipo1: "Argelia",
    equipo2: "Austria",
    flag1: "https://flagcdn.com/dz.svg",
    flag2: "https://flagcdn.com/at.svg",
    estadio: "Estadio Kansas City (Kansas City)",
    fecha: "2026-06-27T00:00:00.000Z",
    grupo: "J",
    precio: "180",
    resultado: "3-3",
    goles1: 3,
    goles2: 3,
    estado: "finalizado"
  },
  {
    id: "m_j06",
    equipo1: "Jordania",
    equipo2: "Argentina",
    flag1: "https://flagcdn.com/jo.svg",
    flag2: "https://flagcdn.com/ar.svg",
    estadio: "Estadio Dallas (Dallas)",
    fecha: "2026-06-27T00:00:00.000Z",
    grupo: "J",
    precio: "180",
    resultado: "1-3",
    goles1: 1,
    goles2: 3,
    estado: "finalizado"
  },
  {
    id: "m_k01",
    equipo1: "Portugal",
    equipo2: "RD Congo",
    flag1: "https://flagcdn.com/pt.svg",
    flag2: "https://flagcdn.com/cd.svg",
    estadio: "Estadio Houston (Houston)",
    fecha: "2026-06-17T00:00:00.000Z",
    grupo: "K",
    precio: "180",
    resultado: "1-1",
    goles1: 1,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_k02",
    equipo1: "Inglaterra",
    equipo2: "Croacia",
    flag1: "https://flagcdn.com/gb-eng.svg",
    flag2: "https://flagcdn.com/hr.svg",
    estadio: "Estadio Dallas (Dallas)",
    fecha: "2026-06-17T00:00:00.000Z",
    grupo: "K",
    precio: "180",
    resultado: "4-2",
    goles1: 4,
    goles2: 2,
    estado: "finalizado"
  },
  {
    id: "m_k03",
    equipo1: "Ghana",
    equipo2: "Panamá",
    flag1: "https://flagcdn.com/gh.svg",
    flag2: "https://flagcdn.com/pa.svg",
    estadio: "Estadio de Toronto (Toronto)",
    fecha: "2026-06-17T00:00:00.000Z",
    grupo: "K",
    precio: "180",
    resultado: "1-0",
    goles1: 1,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_k04",
    equipo1: "Uzbekistán",
    equipo2: "Colombia",
    flag1: "https://flagcdn.com/uz.svg",
    flag2: "https://flagcdn.com/co.svg",
    estadio: "Estadio Ciudad de México (Ciudad de México)",
    fecha: "2026-06-17T00:00:00.000Z",
    grupo: "K",
    precio: "180",
    resultado: "1-3",
    goles1: 1,
    goles2: 3,
    estado: "finalizado"
  },
  {
    id: "m_k05",
    equipo1: "Portugal",
    equipo2: "Uzbekistán",
    flag1: "https://flagcdn.com/pt.svg",
    flag2: "https://flagcdn.com/uz.svg",
    estadio: "Estadio Houston (Houston)",
    fecha: "2026-06-23T00:00:00.000Z",
    grupo: "K",
    precio: "180",
    resultado: "5-0",
    goles1: 5,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_k06",
    equipo1: "Colombia",
    equipo2: "RD Congo",
    flag1: "https://flagcdn.com/co.svg",
    flag2: "https://flagcdn.com/cd.svg",
    estadio: "Estadio Guadalajara (Guadalajara)",
    fecha: "2026-06-23T00:00:00.000Z",
    grupo: "K",
    precio: "180",
    resultado: "1-0",
    goles1: 1,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_l01",
    equipo1: "Inglaterra",
    equipo2: "Croacia",
    flag1: "https://flagcdn.com/gb-eng.svg",
    flag2: "https://flagcdn.com/hr.svg",
    estadio: "Estadio Dallas (Dallas)",
    fecha: "2026-06-17T00:00:00.000Z",
    grupo: "L",
    precio: "180",
    resultado: "4-2",
    goles1: 4,
    goles2: 2,
    estado: "finalizado"
  },
  {
    id: "m_l02",
    equipo1: "Ghana",
    equipo2: "Panamá",
    flag1: "https://flagcdn.com/gh.svg",
    flag2: "https://flagcdn.com/pa.svg",
    estadio: "Estadio de Toronto (Toronto)",
    fecha: "2026-06-17T00:00:00.000Z",
    grupo: "L",
    precio: "180",
    resultado: "1-0",
    goles1: 1,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_l03",
    equipo1: "Inglaterra",
    equipo2: "Ghana",
    flag1: "https://flagcdn.com/gb-eng.svg",
    flag2: "https://flagcdn.com/gh.svg",
    estadio: "Estadio Boston (Boston)",
    fecha: "2026-06-23T00:00:00.000Z",
    grupo: "L",
    precio: "180",
    resultado: "0-0",
    goles1: 0,
    goles2: 0,
    estado: "finalizado"
  },
  {
    id: "m_l04",
    equipo1: "Panamá",
    equipo2: "Croacia",
    flag1: "https://flagcdn.com/pa.svg",
    flag2: "https://flagcdn.com/hr.svg",
    estadio: "Estadio de Toronto (Toronto)",
    fecha: "2026-06-23T00:00:00.000Z",
    grupo: "L",
    precio: "180",
    resultado: "0-1",
    goles1: 0,
    goles2: 1,
    estado: "finalizado"
  },
  {
    id: "m_l05",
    equipo1: "Panamá",
    equipo2: "Inglaterra",
    flag1: "https://flagcdn.com/pa.svg",
    flag2: "https://flagcdn.com/gb-eng.svg",
    estadio: "Estadio Nueva York/Nueva Jersey (Nueva Jersey)",
    fecha: "2026-06-27T00:00:00.000Z",
    grupo: "L",
    precio: "180",
    resultado: "0-2",
    goles1: 0,
    goles2: 2,
    estado: "finalizado"
  },
  {
    id: "m_l06",
    equipo1: "Croacia",
    equipo2: "Ghana",
    flag1: "https://flagcdn.com/hr.svg",
    flag2: "https://flagcdn.com/gh.svg",
    estadio: "Estadio Filadelfia (Filadelfia)",
    fecha: "2026-06-27T00:00:00.000Z",
    grupo: "L",
    precio: "180",
    resultado: "2-1",
    goles1: 2,
    goles2: 1,
    estado: "finalizado"
  }
];